server.servlet.context-path=${CONTEXT_PATH:/umlp/api}
server.port=${PORT:8081}
umlp.service.websocket.impl=noAuth

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#spring.sql.init.mode=always
# No caching in browser during dev, otherwise old versions are displayed
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

smart-grid.polling.url=${SMART_GRID_POLLING_URL:http://localhost:8090/available-energy}
smart-grid.polling.interval-ms=${SMART_GRID_POLLING_INTERVAL_MS:5000}
smart-grid.polling.timeout-ms=${SMART_GRID_POLLING_TIMEOUT_MS:2000}
