/* (c) https://github.com/MontiCore/monticore */

plugins {
  id 'de.rwth.se.montigem-frontend' version "$mg_version"
  id "de.rwth.se.montigem-dt-frontend" version "$mg_version"
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

group = 'de.se-rwth.dt.labdt'
tasks.withType(Jar).configureEach {
  archiveBaseName.set("labdt-frontend")
}
